version: '3.6'
services:
  funny-project-fe:
    build: ../funny-project-fe
    networks:
      - default
    environment:
      REACT_APP_DOMAIN: "http://localhost:3000"
      REACT_APP_API_URL: "http://localhost:8080/funny-project"
      REACT_APP_API_URL_WEB_SOCKET: "ws://localhost:8080/funny-project"
      REACT_APP_GOOGLE_CLIENT_ID: "424064337429-p9uh10or075o6ec44c6i94nua5q6lqq7.apps.googleusercontent.com"
      REACT_APP_SESSION_COOKIE_NAME: "token"
    restart: always
    ports:
      - 3000:80
  funny-project-be:
    build: ./
    networks:
      - default
    environment:
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_HOST: "host.docker.internal"
      DB_NAME: postgres
      DB_PORT: 5433
    restart: always
    volumes:
      - ".:/api"
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - default
    restart: always

networks:
  default:
    name: funny